travis:
  secure:
    BINSTAR_TOKEN: Es++ftQg2Z8iHdkxM4FJd4DrpYbdVmBBcKb3HMdkRnbczl8VlCq1qMni8aMAl3K0ucXa1wSlqx33xb64ENFVPXOaMkoVzQsRJAVzSTv0n+xdF9Sw8uWCN3K6MJFGqQb18YUuerMeG9B/+8T3nItYHIbnJeltatlJiq8aUSbA/jJQ1wbbFaaBJybuqvWUtURXjeAdn6LqVQ8vHs59mExXMx8Me6gCUSaURO4ApARWAtIieCXzm4dacRE3bojqJ9PehgbQYp+Ez+LMJDF55EovPxFEZ9YWXB9WdMKfhZVmNOZ1KBOyF1vqZ8Cmb4lKaQkHoR6dS8LVQ0rVMLC5w5qXEXZrX8pOhgC3nU/7C3zxkkHlfG8K/7uNPF1RgR5RyvekR8NIe8tyBrVLnxnZs7KTWVVmLfapa8jOWRdPfuc3jEiP9wYHwcbOUI3Jd80Y+ofZpWbL4CaihPdRSYXuc17SjEZ2grGOUFqLBosO6vtLSEg0M4WFziWir7phn5BfNnHtufEcj6rXcLGxlAnmyg1woZO3AtZavb4RaNrImEI94sz0t2HH2OKSouu+EdySlx16tUdhpAi4PlF1XkWEByie2AfS0FHPRiRXidcRy2FiwvZR7CQflr7flYuuFN1euA+T/m8K6zvENOPIWO3Ekof7qOpCt3Md7ivnb4jEwqdJLZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
